// Notification 

export const GET_GIFT_DATA__BY_ID = 'GET_GIFT_DATA__BY_ID';
export const SET_GIFT_DATA__BY_ID = 'SET_GIFT_DATA__BY_ID';

export const GET_RECHARGE_BANNER = 'GET_RECHARGE_BANNER'
export const SET_RECHARGE_BANNER = 'SET_RECHARGE_BANNER'

export const GET_NOTIFICATION_DATA = 'GET_NOTIFICATION_DATA';
export const SET_NOTIFICATION_DATA = 'SET_NOTIFICATION_DATA';

export const SHOW_PAYMENT_RESULT_MODAL = 'SHOW_PAYMENT_RESULT_MODAL';
export const HIDE_PAYMENT_RESULT_MODAL = 'HIDE_PAYMENT_RESULT_MODAL';

export const SET_VIDEO_ID = 'SET_VIDEO_ID';

// delete account

export const GET_DELETE_ACCOUNT_DATA = 'GET_DELETE_ACCOUNT_DATA';
export const SET_DELETE_ACCOUNT_DATA = 'SET_DELETE_ACCOUNT_DATA';

// pooja 
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const GET_POOJA_DATA = 'GET_POOJA_DATA';
export const SET_POOJA_DATA = 'SET_POOJA_DATA';
export const GET_NEW_POOJA_DATA = 'GET_NEW_POOJA_DATA';
export const SET_NEW_POOJA_DATA = 'SET_NEW_POOJA_DATA';
export const GET_ALL_POOJA_LIST = 'GET_ALL_POOJA_LIST ';
export const SET_ALL_POOJA_LIST = 'SET_ALL_POOJA_LIST ';
export const GET_BOOK_POOJA = 'GET_BOOK_POOJA';
export const SET_BOOK_POOJA = 'SET_BOOK_POOJA';
export const GET_BOOK_POOJA_HISTORY_DATA = 'GET_BOOK_POOJA_HISTORY_DATA';
export const SET_BOOK_POOJA_HISTORY_DATA = 'SET_BOOK_POOJA_HISTORY_DATA'

//Setings
export const GET_SPLASH = 'GET_SPLASH';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_REFRESHING = 'SET_IS_REFRESHING';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_IMAGE_PICKER_VISIBLE = 'SET_IMAGE_PICKER_VISIBLE'
export const SET_IS_MORE_LOADING = 'SET_IS_MORE_LOADING'
export const SET_SUB_LOCATION_DATA = 'SET_SUB_LOCATION_DATA'
export const ON_UPDATE_PIN = 'ON_UPDATE_PIN'

//Auth
export const ON_LOGIN = 'ON_LOGIN';
export const ON_GOOGLE_LOGIN = 'ON_GOOGLE_LOGIN';
export const ON_OTP_VERIFICATION = 'ON_OTP_VERIFICATION';
export const ON_REGISTER = 'ON_REGISTER';
export const ON_APPLY_AS_AN_ASTROLOGER = 'ON_APPLY_AS_AN_ASTROLOGER';

//Customer
export const SET_CUSTOMER_DATA = 'SET_CUSTOMER_DATA';
export const GET_CUSTOMER_DATA = 'GET_CUSTOMER_DATA';
export const ON_WALLET_RECHARGE = 'ON_WALLET_RECHARGE';
export const GET_FOLLOWING_LIST = 'GET_FOLLOWING_LIST';
export const SET_FOLLOWING_LIST = 'SET_FOLLOWING_LIST';
export const GET_WALLET_RECHARGE_OFFER_LIST = 'GET_WALLET_RECHARGE_OFFER_LIST'
export const SET_WALLET_RECHARGE_OFFER_LIST = 'SET_WALLET_RECHARGE_OFFER_LIST'
export const ON_CUSTOMER_REFERRAL_CODE = 'ON_CUSTOMER_REFERRAL_CODE'
export const GET_DIVYA_HISTORY = 'GET_DIVYA_HISTORY'
export const SET_DIVYA_HISTORY = 'SET_DIVYA_HISTORY'
export const GET_PURUSHARTHA_HISTORY = 'GET_PURUSHARTHA_HISTORY'
export const SET_PURUSHARTHA_HISTORY = 'SET_PURUSHARTHA_HISTORY'

//Home
export const GET_HOME_DATA = 'GET_HOME_DATA';
export const SET_HOME_BANNER = 'SET_HOME_BANNER';
export const SET_CHAT_ASTROLOGER = 'SET_CHAT_ASTROLOGER';
export const SET_CALL_ASTROLOGER = 'SET_CALL_ASTROLOGER';
export const SET_VIDEO_CALL_ASTROLOGER = 'SET_VIDEO_CALL_ASTROLOGER'
export const SET_HOME_SIMMER = 'SET_HOME_SIMMER';
export const GET_HOME_DATA_ON_REFRESH = 'GET_HOME_DATA_ON_REFRESH';
export const GET_ASTRO_COMPANION_DATA = 'GET_ASTRO_COMPANION_DATA';
export const SET_ASTRO_COMPANION_DATA = 'SET_ASTRO_COMPANION_DATA';
export const SET_HOME_TEMPLE_FOUNDATION = 'SET_HOME_TEMPLE_FOUNDATION';
export const SET_HOME_TREERTH_DHAM = 'SET_HOME_TREERTH_DHAM';
export const SET_TEMPLE_VIDEOS = 'SET_TEMPLE_VIDEOS';

//Astrologer
export const GET_ASTROLOGER_DATA = 'GET_ASTROLOGER_DATA';
export const SET_ASTROLOGER_DATA = 'SET_ASTROLOGER_DATA';
export const SET_ASTROLOGER_REVIEW_DATA = 'SET_ASTROLOGER_REVIEW_DATA';
export const GET_LIVE_ASTROLOGER_DATA = 'GET_LIVE_ASTROLOGER_DATA';
export const SET_LIVE_ASTROLOGER_DATA = 'SET_LIVE_ASTROLOGER_DATA';
export const GET_RECENT_LIVESTREAMINGS = 'GET_RECENT_LIVESTREAMINGS'
export const SET_RECENT_LIVESTREAMINGS = 'SET_RECENT_LIVESTREAMINGS'
export const ON_REFRESH_LIVE_ASTROLOGER = 'ON_REFRESH_LIVE_ASTROLOGER';
export const GET_CALL_ASTROLOGERS = 'GET_CALL_ASTROLOGERS';
export const GET_MORE_CALL_ASTROLOGERS = 'GET_MORE_CALL_ASTROLOGERS'
export const GET_MORE_CHAT_ASTROLOGERS = 'GET_MORE_CHAT_ASTROLOGERS'
export const SET_CALL_ASTROLOGERS = 'SET_CALL_ASTROLOGERS';
export const ON_REFRESH_CALL_ASTROLOGER = 'ON_REFRESH_CALL_ASTROLOGER';
export const GET_CHAT_ASTROLOGERS = 'GET_CHAT_ASTROLOGERS';
export const SET_CHAT_ASTROLOGERS = 'SET_CHAT_ASTROLOGERS';
export const ON_REFRESH_CHAT_ASTROLOGER = 'ON_REFRESH_CHAT_ASTROLOGER';
export const ON_CALL_TO_ASTROLOGER = 'ON_CALL_TO_ASTROLOGER';
export const ON_VIDEO_CALL_TO_ASTROLOGER = 'ON_VIDEO_CALL_TO_ASTROLOGER'
export const SET_ASTRO_RATING_VISIBLE = 'SET_ASTRO_RATING_VISIBLE'
export const ON_ASTRO_RATING = 'ON_ASTRO_RATING'
export const ON_FOLLOW_UNFOLLOW_ASTROLOGER = 'ON_FOLLOW_UNFOLLOW_ASTROLOGER'
export const ON_CHECK_IS_FOLLOW = 'ON_CHECK_IS_FOLLOW'
export const SET_IS_FOLLOW_ASTROLOGER = 'SET_IS_FOLLOW_ASTROLOGER'
export const GET_VIDEO_CALL_ASTROLOGERS = 'GET_VIDEO_CALL_ASTROLOGERS'
export const SET_VIDEO_CALL_ASTROLOGERS = 'SET_VIDEO_CALL_ASTROLOGERS'

//Live
export const SET_LIVE_ID = 'SET_LIVE_ID';;
export const CREATE_LIVE_PROFILE = 'CREATE_LIVE_PROFILE';
export const ADD_LIVE_LISTENER = 'ADD_LIVE_LISTENER';
export const SEND_COMMENTS = 'SEND_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const SET_GIFT_DATA = 'SET_GIFT_DATA';
export const SET_GIFT_VISIBLE = 'SET_GIFT_VISIBLE';
export const GET_GIFT_DATA = 'GET_GIFT_DATA';
export const SEND_GIFT_TO_ASTROLOGER = 'SEND_GIFT_TO_ASTROLOGER';
export const ADD_HEART = 'ADD_HEART';
export const REMOVE_HEART = 'REMOVE_HEART';
export const SET_HEARTS = 'SET_HEARTS';
export const SET_EXIT_ALERT_VISIBLE = 'SET_EXIT_ALERT_VISIBLE';
export const SET_IS_LIVE_START = 'SET_IS_LIVE_START';
export const SET_ROOM_USER_COUNT = 'SET_ROOM_USER_COUNT';
export const SET_LIVE_CALLS_VISIBLE = 'SET_LIVE_CALLS_VISIBLE';
export const SET_WAITING_LIST_VISIBLE = 'SET_WAITING_LIST_VISIBLE';
export const ADD_IN_WAITING_LIST = 'ADD_IN_WAITING_LIST';
export const SET_WAITLIST_DATA = 'SET_WAITLIST_DATA';
export const SET_CO_HOST_REQUEST_VISIBLE = 'SET_CO_HOST_REQUEST_VISIBLE';
export const SET_IS_CO_HOST = 'SET_IS_CO_HOST';
export const SET_STREAMING_ID = 'SET_STREAMING_ID';
export const ON_GO_LIVE = 'ON_GO_LIVE';
export const SET_LAYOUT = 'SET_LAYOUT';
export const RESET_LIVE_STATE = 'RESET_LIVE_STATE';
export const SET_CO_HOST_DATA = 'SET_CO_HOST_DATA';
export const ON_END_CALLING = 'ON_END_CALLING';
export const SET_GIFTED_DATA = 'SET_GIFTED_DATA';
export const ON_CANCEL_CALL_REQUEST = 'ON_CANCEL_CALL_REQUEST'
export const SET_LIVE_ASTRO_DATA = 'SET_LIVE_ASTRO_DATA'
export const SET_LIVE_DATA = 'SET_LIVE_DATA'
export const ADD_HEART_BY_OTHERS = 'ADD_HEART_BY_OTHERS'
export const ON_STREAM_UPDATE = 'ON_STREAM_UPDATE'
export const SET_CALL_INFO_VISIBLE = 'SET_CALL_INFO_VISIBLE'
export const SET_LIVE_INVOICE_VISIBLE = 'SET_LIVE_INVOICE_VISIBLE'
export const ON_LIVE_MUTE_UNMUTE = 'ON_LIVE_MUTE_UNMUTE'
export const SET_LIVE_IS_MUTE = 'SET_LIVE_IS_MUTE'
export const ON_APP_STATE_CHANGE_IN_LIVE = 'ON_APP_STATE_CHANGE_IN_LIVE'


//Chat Call videcall
export const GET_ON_VIDEO_CALL_END = 'GET_ON_VIDEO_CALL_END';
export const SET_ON_VIDEO_CALL_END = 'SET_ON_VIDEO_CALL_END';
export const SET_VIDEO_INVOICE_DATA = 'SET_VIDEO_INVOICE_DATA';
export const ON_CHAT_NOW = 'ON_CHAT_NOW'
export const ON_CALL_NOW = 'ON_CALL_NOW'
export const GET_MY_LINKED_PROFILE = 'GET_MY_LINKED_PROFILE'
export const ON_CHAT_REQUEST_SEND = 'ON_CHAT_REQUEST_SEND'
export const SET_LINKED_PROFILE = 'SET_LINKED_PROFILE'
export const ON_ACCEPT_REJECT_CHAT = 'ON_ACCEPT_REJECT_CHAT'
export const SET_CHAT_TIMER_COUNTDOWN = 'SET_CHAT_TIMER_COUNTDOWN'
export const SET_CHAT_DATA = 'SET_CHAT_DATA'
export const SET_CHAT_REQUESTED_DATA = 'SET_CHAT_REQUESTED_DATA'
export const ON_INITIATE_CHAT = 'ON_INITIATE_CHAT'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const SAVE_CHAT_MESSAGE = 'SAVE_CHAT_MESSAGE'
export const ON_END_CHAT = 'ON_END_CHAT'
export const ON_CLOSE_CHAT = 'ON_CLOSE_CHAT'
export const ON_CHAT_IMAGE_SEND = 'ON_CHAT_IMAGE_SEND'
export const SET_CHAT_IMAGE_DATA = 'SET_CHAT_IMAGE_DATA'
export const ON_RECONNECT_CHAT = 'ON_RECONNECT_CHAT'
export const SET_CALL_INVOICE_VISIBLE = 'SET_CALL_INVOICE_VISIBLE'
export const SET_VIDEOCALL_INVOICE_VISIBLE = 'SET_VIDEOCALL_INVOICE_VISIBLE'
export const SET_CALL_INVOICE_DATA = 'SET_CALL_INVOICE_DATA'
export const SET_CHAT_INVOICE_VISIBLE = 'SET_CHAT_INVOICE_VISIBLE'
export const SET_CHAT_INVOICE_DATA = 'SET_CHAT_INVOICE_DATA'
export const SET_CHAT_CALL_DATA_SAVE = 'SET_CHAT_CALL_DATA_SAVE';
export const ON_CHAT_CALL_CHECK = 'ON_CHAT_CALL_CHECK';
export const GET_LINKED_DATA = 'GET_LINKED_DATA';
export const SET_LINKED_DATA = 'SET_LINKED_DATA';
export const SET_CAMERA_VISION_VISIBLE = 'SET_CAMERA_VISION_VISIBLE';
export const SET_CHAT_REPLAY = 'SET_CHAT_REPLAY';

//History
export const GET_CHAT_HISTORY = 'GET_CHAT_HISTORY'
export const SET_CHAT_HISTORY = 'SET_CHAT_HISTORY'
export const GET_CALL_HISTORY = 'GET_CALL_HISTORY'
export const SET_CALL_HISTORY = 'SET_CALL_HISTORY'
export const GET_LIVE_VEDIO_CALL_HISTORY = 'GET_LIVE_VEDIO_CALL_HISTORY'
export const SET_LIVE_VEDIO_CALL_HISTORY = 'SET_LIVE_VEDIO_CALL_HISTORY'
export const GET_WALLET_HISTORY = 'GET_WALLET_HISTORY';
export const SET_WALLET_HISTORY = 'SET_WALLET_HISTORY';
export const GET_VIDEO_CALL_HISTORY = 'GET_VIDEO_CALL_HISTORY'
export const SET_VIDEO_CALL_HISTORY = 'SET_VIDEO_CALL_HISTORY'

export const GET_RECHARGE_HISTORY = 'GET_RECHARGE_HISTORY'
export const SET_RECHARGE_HISTORY = 'SET_RECHARGE_HISTORY'


export const SET_KP_PLANET_CUPS_DATA = 'SET_KP_PLANET_CUPS_DATA';
export const GET_KP_PLANET_CUPS_DATA = 'GET_KP_PLANET_CUPS_DATA';
export const SET_KP_BIRTH_DETAILS = 'SET_KP_BIRTH_DETAILS';
export const GET_KP_BIRTH_DETAILS = 'GET_KP_BIRTH_DETAILS';

//Kundli
export const SET_KUNDLI_PAYLOADS = 'SET_KUNDLI_PAYLOADS'
export const RESET_KUNDLI_DATA = 'RESET_KUNDLI_DATA'
export const CREATE_KUNDLI = 'CREATE_KUNDLI'

export const GET_CREATE_KUNDLI = 'GET_CREATE_KUNDLI'
export const SET_CREATE_KUNDLI = 'SET_CREATE_KUNDLI'

export const GET_ALL_KUNDLI = 'GET_ALL_KUNDLI'
export const SET_ALL_KUNDLI = 'SET_ALL_KUNDLI'
export const SET_ALL_MASTRER_KUNDLI = 'SET_ALL_MASTRER_KUNDLI'
export const DELETE_KUNDLI = 'DELETE_KUNDLI'
export const GET_KUNDLI_DATA = 'GET_KUNDLI_DATA'
export const SET_KUNDLI_ID = 'SET_KUNDLI_ID'
export const GET_KUNDLI_BIRTH_DETAILS = 'GET_KUNDLI_BIRTH_DETAILS'
export const SET_KUNDLI_BIRTH_DETAILS = 'SET_KUNDLI_BIRTH_DETAILS'
export const GET_KUNDLI_CHART_DATA = 'GET_KUNDLI_CHART_DATA'
export const SET_KUNDLI_CHARTS = 'SET_KUNDLI_CHARTS';
export const SET_CHALIT_KUNDLI_CHARTS = 'SET_CHALIT_KUNDLI_CHARTS';
export const SET_KUNDLI_CHARTS_IMAGE = 'SET_KUNDLI_CHARTS_IMAGE'
export const GET_KUNDLI_CHARTS_IMAGE = 'SET_KUNDLI_CHARTS_IMAGE'
export const SET_KUNDLI_BASIC_DETAILS = 'SET_KUNDLI_BASIC_DETAILS'
export const SET_PLANET_DATA = 'SET_PLANET_DATA'
export const GET_PLANET_DATA = 'GET_PLANET_DATA'



export const GET_HOUSES_DATA = 'GET_PLANET_DATA'
export const SET_HOUSES_DATA = 'SET_HOUSES_DATA'

export const GET_SADHESATIBRIEF_DATA = 'GET_SADHESATIBRIEF_DATA'
export const SET_SADHESATIBRIEF_DATA = 'SET_SADHESATIBRIEF_DATA'


export const GET_SADHESATI_REMEDIES = 'GET_SADHESATI_REMEDIES'
export const SET_SADHESATI_REMEDIES = 'SET_SADHESATI_REMEDIES'

export const GET_SADHESATI_RUNNING = 'GET_SADHESATI_RUNNING'
export const SET_SADHESATI_RUNNING = 'SET_SADHESATI_RUNNING'

export const GET_ASCENDENT_DATA = 'GET_ASCENDENT_DATA'
export const SET_ASCENDENT_DATA = 'SET_ASCENDENT_DATA'


export const GET_MANGLIK_REMEDIES = 'GET_MANGLIK_REMEDIES'
export const SET_MANGLIK_REMEDIES = 'SET_MANGLIK_REMEDIES'

export const GET_MANGLIK_REPORT = 'GET_MANGLIK_REPORT'
export const SET_MANGLIK_REPORT = 'SET_MANGLIK_REPORT'


export const GET_SADHBHAL_DATA = 'GET_SADHBHAL_DATA'
export const SET_SADHBHAL_DATA = 'SET_SADHBHAL_DATA'


export const GET_NUM_TABLE_DATA = 'GET_NUM_TABLE_DATA'
export const SET_NUM_TABLE_DATA = 'SET_NUM_TABLE_DATA'

export const GET_AVAKHADA = 'GET_AVAKHADA'
export const SET_AVAKHADA = 'SET_AVAKHADA'


export const GET_NUM_TABLE_CHART = 'GET_NUM_TABLE_CHART'
export const SET_NUM_TABLE_CHART = 'SET_NUM_TABLE_CHART'


export const GET_GEO_DATA = 'GET_GEO_DATA'
export const SET_GEO_DATA = 'SET_GEO_DATA'

export const GET_KALREMEDIES_DATA = 'GET_KALREMEDIES_DATA'
export const SET_KALREMEDIES_DATA = 'SET_KALREMEDIES_DATA'

export const GET_BIRTH_NAK_DATA = 'GET_BIRTH_NAK_DATA'
export const SET_BIRTH_NAK_DATA = 'SET_BIRTH_NAK_DATA'


export const GET_FORECAST_DATA = 'GET_FORECAST_DATA'
export const SET_FORECAST_DATA = 'SET_FORECAST_DATA'

export const GET_VINHOTTARI_PREDICTION_DATA = 'GET_VINHOTTARI_PREDICTION_DATA'
export const SET_VINHOTTARI_PREDICTION_DATA = 'SET_VINHOTTARI_PREDICTION_DATA'


export const GET_TRANSIT = 'GET_TRANSIT'
export const SET_TRANSIT = 'SET_TRANSIT'

export const GET_HOROSCOPE_PREDICTION_DATA = 'GET_HOROSCOPE_PREDICTION_DATA'
export const SET_HOROSCOPE_PREDICTION_DATA = 'SET_HOROSCOPE_PREDICTION_DATA'


export const GET_PERSNALITY_DATA = 'GET_PERSNALITY_DATA'
export const SET_PERSNALITY_DATA = 'SET_PERSNALITY_DATA'

export const GET_DESTINATION_DATA = 'GET_DESTINATION_DATA'
export const SET_DESTINATION_DATA = 'SET_DESTINATION_DATA'


export const GET_LAALKITAAB_DATA = 'GET_LAALKITAAB_DATA'
export const SET_LAALKITAAB_DATA = 'SET_LAALKITAAB_DATA'


export const GET_NAKSHATRA_DATA = 'GET_NAKSHATRA_DATA'
export const SET_NAKSHATRA_DATA = 'SET_NAKSHATRA_DATA'


export const GET_FINANCE_DATA = 'GET_FINANCE_DATA'
export const SET_FINANCE_DATA = 'SET_FINANCE_DATA'


export const GET_GEMSTONE_DATA = 'GET_GEMSTONE_DATA'
export const SET_GEMSTONE_DATA = 'SET_GEMSTONE_DATA'

export const GET_HEALTHSTONE_DATA = 'GET_HEALTHSTONE_DATA'
export const SET_HEALTHSTONE_DATA = 'SET_HEALTHSTONE_DATA'

export const GET_EDUCATION_STONE_DATA = 'GET_EDUCATION_STONE_DATA'
export const SET_EDUCATION_STONE_DATA = 'SET_EDUCATION_STONE_DATA'

export const GET_DAAN_STONE_DATA = 'GET_DAAN_STONE_DATA'
export const SET_DAAN_STONE_DATA = 'SET_DAAN_STONE_DATA'



export const GET_YANTRA_DATA = 'GET_YANTRA_DATA'
export const SET_YANTRA_DATA = 'SET_YANTRA_DATA'



export const GET_MANTRA_DATA = 'GET_MANTRA_DATA'
export const SET_MANTRA_DATA = 'SET_MANTRA_DATA'




export const GET_RUDHRAKSHA_DATA = 'GET_RUDHRAKSHA_DATA'
export const SET_RUDHRAKSHA_DATA = 'SET_RUDHRAKSHA_DATA'

export const GET_TARROT_DATA = 'GET_TARROT_DATA'
export const SET_TARROT_DATA = 'SET_TARROT_DATA'


export const GET_NEW_FINANCE_DATA = 'GET_NEW_FINANCE_DATA';
export const SET_NEW_FINANCE_DATA = 'SET_NEW_FINANCE_DATA';

export const GET_NEW_ROMANACE_DATA = 'GET_NEW_ROMANACE_DATA';
export const SET_NEW_ROMANACE_DATA = 'SET_NEW_ROMANACE_DATA';

export const GET_NEW_PROFESSION_DATA = 'GET_NEW_PROFESSION_DATA';
export const SET_NEW_PROFESSION_DATA = 'SET_NEW_PROFESSION_DATA';


export const GET_NEW_HEALTH_MIND_DATA = 'GET_NEW_HEALTH_MIND_DATA';
export const SET_NEW_HEALTH_MIND_DATA = 'SET_NEW_HEALTH_MIND_DATA';


export const GET_LUCK_REPORT_DATA = 'GET_LUCK_REPORT_DATA';
export const SET_LUCK_REPORT_DATA = 'SET_LUCK_REPORT_DATA';

export const GET_PHILOSPHY_DATA = 'GET_PHILOSPHY_DATA';
export const SET_PHILOSPHY_DATA = 'SET_PHILOSPHY_DATA';



//LETTER TO GOD ACTIONSTYPES


export const GET_WELCOME_MESSAGE = 'GET_WELCOME_MESSAGE'
export const SET_WELCOME_MESSAGE = 'SET_WELCOME_MESSAGE'


export const GET_SAVED_PROFILES = 'GET_SAVED_PROFILES'
export const SET_SAVED_PROFILES = 'SET_SAVED_PROFILES'


export const GET_SAVE_MESSAGES = 'GET_SAVE_MESSAGES'
export const SET_SAVE_MESSAGES = 'SET_SAVE_MESSAGES'


export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA'
export const SET_CATEGORY_DATA = 'SET_CATEGORY_DATA'



export const GET_CHAT_HISTORY_LETTER = 'GET_CHAT_HISTORY_LETTER'
export const SET_CHAT_HISTORY_LETTER = 'SET_CHAT_HISTORY_LETTER'


export const GET_QUESTIONS_DATA = 'GET_QUESTIONS_DATA'
export const SET_QUESTIONS_DATA = 'SET_QUESTIONS_DATA'


export const GET_ANSWERS_DATA = 'GET_ANSWERS_DATA'
export const SET_ANSWERS_DATA = 'SET_ANSWERS_DATA'

export const GET_RELATED_QUESTIONS = 'GET_RELATED_QUESTIONS'
export const SET_RELATED_QUESTIONS = 'SET_RELATED_QUESTIONS'


export const GET_CHAT_GPT_SEARCH = 'GET_CHAT_GPT_SEARCH'
export const SET_CHAT_GPT_SEARCH = 'SET_CHAT_GPT_SEARCH'


export const GET_DIVYA_PLANS = 'GET_DIVYA_PLANS'
export const SET_DIVYA_PLANS = 'SET_DIVYA_PLANS'

export const GET_BUY_PLANS = 'GET_BUY_PLANS'
export const SET_BUY_PLANS = 'SET_BUY_PLANS'


export const GET_PLANS_HISTORY = 'GET_PLANS_HISTORY'
export const SET_PLANS_HISTORY = 'SET_PLANS_HISTORY'


export const GET_USER_DATA_DB = 'GET_USER_DATA_DB'
export const SET_USER_DATA_DB = 'SET_USER_DATA_DB'



export const GET_HOUSE_DATA = 'GET_HOUSE_DATA'
export const SET_HOUSE_DATA = 'SET_HOUSE_DATA'

export const GET_RASHI_DATA = 'GET_RASHI_DATA'
export const SET_RASHI_DATA = 'SET_RASHI_DATA'

export const GET_NUM_PRIDICTION_DATA = 'GET_NUM_PRIDICTION_DATA'
export const SET_NUM_PRIDICTION_DATA = 'SET_NUM_PRIDICTION_DATA'


export const GET_NUM_NAME_DATA = 'GET_NUM_NAME_DATA'
export const SET_NUM_NAME_DATA = 'SET_NUM_NAME_DATA'


export const GET_NUM_YEAR_DATA = 'GET_NUM_YEAR_DATA'
export const SET_NUM_YEAR_DATA = 'SET_NUM_YEAR_DATA'


export const GET_NUM_MONTHLY_DATA = 'GET_NUM_MONTHLY_DATA'
export const SET_NUM_MONTHLY_DATA = 'SET_NUM_MONTHLY_DATA'


export const GET_NUM_DAY_DATA = 'GET_NUM_DAY_DATA'
export const SET_NUM_DAY_DATA = 'SET_NUM_DAY_DATA'


export const GET_PHILOSPY_DATA = 'GET_PHILOSPY_DATA'
export const SET_PHILOSPY_DATA = 'SET_PHILOSPY_DATA'

export const GET_ROMANTIC_DATA = 'GET_ROMANTIC_DATA'
export const SET_ROMANTIC_DATA = 'SET_ROMANTIC_DATA'



export const GET_ANTAR_DASHA = 'GET_ANTAR_DASHA'
export const SET_ANTAR_DASHA = 'SET_ANTAR_DASHA'


export const GET_PRANYANANTAR_DASHA = 'GET_PRANYANANTAR_DASHA'
export const SET_PRANYANANTAR_DASHA = 'SET_PRANYANANTAR_DASHA'


export const GET_SOOKHAM_DASHA = 'GET_SOOKHAM_DASHA'
export const SET_SOOKHAM_DASHA = 'SET_SOOKHAM_DASHA'


// Letter to god actintypes

export const GET_LETTER_LAGNA_CHART = 'GET_LETTER_LAGNA_CHART';
export const SET_LETTER_LAGNA_CHART = 'SET_LETTER_LAGNA_CHART';


export const GET_LETTER_NAVMANSHA_CHART = 'GET_LETTER_NAVMANSHA_CHART';
export const SET_LETTER_NAVMANSHA_CHART = 'SET_LETTER_NAVMANSHA_CHART';


export const GET_LETTER_DASHMANSHA_CHART = 'GET_LETTER_DASHMANSHA_CHART';
export const SET_LETTER_DASHMANSHA_CHART = 'SET_LETTER_DASHMANSHA_CHART';

export const GET_LETTER_BIRTH_CHART = 'GET_LETTER_BIRTH_CHART';
export const SET_LETTER_BIRTH_CHART = 'SET_LETTER_BIRTH_CHART';


export const GET_KP_PLANETS_LETTERWAALA = 'GET_KP_PLANETS_LETTERWAALA';
export const SET_KP_PLANETS_LETTERWAALA = 'SET_KP_PLANETS_LETTERWAALA';



export const GET_HORA_CHART = 'GET_HORA_CHART';
export const SET_HORA_CHART = 'SET_HORA_CHART';

export const GET_PLANETS_UPGRAHA = 'GET_PLANETS_UPGRAHA';
export const SET_PLANETS_UPGRAHA = 'SET_PLANETS_UPGRAHA';

export const GET_PLANETS_DASHAMBHAV = 'GET_PLANETS_DASHAMBHAV';
export const SET_PLANETS_DASHAMBHAV = 'SET_PLANETS_DASHAMBHAV';

export const GET_MY_ASTRO = 'GET_MY_ASTRO';
export const SET_MY_ASTRO = 'SET_MY_ASTRO';

export const GET_MY_FRIENDDATA = 'GET_MY_FRIENDDATA';
export const SET_MY_FRIENDDATA = 'SET_MY_FRIENDDATA';

export const GET_MY_PREDICTION = 'GET_MY_PREDICTION';
export const SET_MY_PREDICTION = 'SET_MY_PREDICTION';

export const GET_MY_BIRTH_DETAILES = 'GET_MY_BIRTH_DETAILES';
export const SET_MY_BIRTH_DETAILES = 'SET_MY_BIRTH_DETAILES';


export const GET_LETTER_BIRTH = 'GET_LETTER_BIRTH';
export const SET_LETTER_BIRTH = 'SET_LETTER_BIRTH';


export const GET_MY_SARVASATK = 'GET_MY_SARVASATK';
export const SET_MY_SARVASATK = 'SET_MY_SARVASATK';

export const GET_MY_ASTAKVARGA = 'GET_MY_ASTAKVARGA';
export const SET_MY_ASTAKVARGA = 'SET_MY_ASTAKVARGA';

export const GET_MY_CHARANTAR = 'GET_MY_CHARANTAR';
export const SET_MY_CHARANTAR = 'SET_MY_CHARANTAR';


export const GET_MY_ASTRO_MATCHING_NEW = 'GET_MY_ASTRO_MATCHING_NEW';
export const SET_MY_ASTRO_MATCHING_NEW = 'SET_MY_ASTRO_MATCHING_NEW';


export const GET_MY_ASTAKOOTA_DATA = 'GET_MY_ASTAKOOTA_DATA';
export const SET_MY_ASTAKOOTA_DATA = 'SET_MY_ASTAKOOTA_DATA';


export const GET_MY_ALL_HOROSCOPE = 'GET_MY_ALL_HOROSCOPE';
export const SET_MY_ALL_HOROSCOPE = 'SET_MY_ALL_HOROSCOPE';



export const GET_MY_NUM = 'GET_MY_NUM';
export const SET_MY_NUM = 'SET_MY_NUM';


export const GET_LUCKY_GEMSTONE = 'GET_LUCKY_GEMSTONE';
export const SET_LUCKY_GEMSTONE = 'SET_LUCKY_GEMSTONE';

export const GET_HEALTH_GEMSTONE = 'GET_HEALTH_GEMSTONE';
export const SET_HEALTH_GEMSTONE = 'SET_HEALTH_GEMSTONE';


export const GET_EDUCATION_GEMSTONE = 'GET_EDUCATION_GEMSTONE';
export const SET_EDUCATION_GEMSTONE = 'SET_EDUCATION_GEMSTONE';


export const GET_LOSHU_GRID = 'GET_LOSHU_GRID';
export const SET_LOSHU_GRID = 'SET_LOSHU_GRID';

export const GET_ARROWS = 'GET_ARROWS';
export const SET_ARROWS = 'SET_ARROWS';

export const GET_EXPRESSIONS = 'GET_EXPRESSIONS';
export const SET_EXPRESSIONS = 'SET_EXPRESSIONS';


export const GET_NEW_LAALKITAAB = 'GET_NEW_LAALKITAAB';
export const SET_NEW_LAALKITAAB = 'SET_NEW_LAALKITAAB';


export const GET_PERSNAL_YEAR = 'GET_PERSNAL_DAY';
export const SET_PERSNAL_YEAR = 'SET_PERSNAL_DAY';


export const GET_PERSNAL_MONTH = 'GET_PERSNAL_MONTH';
export const SET_PERSNAL_MONTH = 'SET_PERSNAL_MONTH';



export const GET_NAME_NUMEROLOGY = 'GET_NAME_NUMEROLOGY';
export const SET_NAME_NUMEROLOGY = 'SET_NAME_NUMEROLOGY';

export const GET_NAME_NUMEROLOGY2 = 'GET_NAME_NUMEROLOGY2';
export const SET_NAME_NUMEROLOGY2 = 'SET_NAME_NUMEROLOGY2';


export const GET_NUM_DAY = 'GET_NUM_DAY';
export const SET_NUM_DAY = 'SET_NUM_DAY';

export const GET_MY_VIMHOTRI = 'GET_MY_VIMHOTRI';
export const SET_MY_VIMHOTRI = 'SET_MY_VIMHOTRI';

export const GET_ANTAR_VIM = 'GET_ANTAR_VIM';
export const SET_ANTAR_VIM = 'SET_ANTAR_VIM';

export const GET_PRATYANTRADESH_DATA = 'GET_PRATYANTRADESH_DATA';
export const SET_PRATYANTRADESH_DATA = 'SET_PRATYANTRADESH_DATA';


export const GET_SOOKHAMDASAHA_DATA = 'GET_SOOKHAMDASAHA_DATA';
export const SET_SOOKHAMDASAHA_DATA = 'SET_SOOKHAMDASAHA_DATA';

export const GET_PRANAMDASA_DATA = 'GET_PRANAMDASA_DATA';
export const SET_PRANAMDASA_DATA = 'SET_PRANAMDASA_DATA';



export const GET_PREDICTION = 'GET_PREDICTION';
export const SET_PREDICTION = 'SET_PREDICTION';

export const GET_SADHESATI = 'GET_SADHESATI';
export const SET_SADHESATI = 'SET_SADHESATI';

export const GET_KAALSARPDOSHA = 'GET_KAALSARPDOSHA';
export const SET_KAALSARPDOSHA = 'SET_KAALSARPDOSHA';

export const GET_GEMINIDATA = 'GET_GEMINIDATA';
export const SET_GEMINIDATA = 'SET_GEMINIDATA';

export const GET_CHARDASHA = 'GET_CHARDASHA';
export const SET_CHARDASHA = 'SET_CHARDASHA';

export const GET_KARKANSHA_CHART = 'GET_KARKANSHA_CHART';
export const SET_KARKANSHA_CHART = 'SET_KARKANSHA_CHART';



//Go With Stepper and Create Kundli

export const GET_NAME_INKUNDLI = 'GET_NAME_INKUNDLI ';
export const SET_NAME_INKUNDLI = 'SET_NAME_INKUNDLI';
export const GET_GENDER_INKUNDLI = 'GET_GENDER_INKUNDLI';
export const SET_GENDER_INKUNDLI = 'SET_GENDER_INKUNDLI';
export const GET_DateOFBIRTH_INKUNDLI = 'GET_DateOFBIRTH_INKUNDLI';
export const SET_DateOFBIRTH_INKUNDLI = 'SET_DateOFBIRTH_INKUNDLI';
export const GET_DateOFTIME_INKUNDLI = 'GET_DateOFTIME_INKUNDLI';
export const SET_DateOFTIME_INKUNDLI = 'SET_DateOFTIME_INKUNDLI';

export const GET_NEW_LINKED_DATA = 'GET_NEW_LINKED_DATA';
export const SET_NEW_LINKED_DATA = 'SET_NEW_LINKED_DATA';

export const GET_GOOGLE_LOGIN_DATA = 'GET_GOOGLE_LOGIN_DATA';
export const SET_GOOGLE_LOGIN_DATA = 'SET_GOOGLE_LOGIN_DATA';

export const GET_MESSAGE_DATA = 'GET_MESSAGE_DATA';
export const SET_MESSAGES_DATA = 'SET_MESSAGES_DATA';



export const SET_KP_PLANET_DATA = 'SET_KP_PLANET_DATA'
export const GET_KP_PLANET_DATA = 'GET_KP_PLANET_DATA'
export const SET_KP_HOUSE_CUPS_DATA = 'SET_KP_HOUSE_CUPS_DATA'
export const GET_KP_HOUSE_CUPS_DATA = 'GET_KP_HOUSE_CUPS_DATA'
export const GET_KUNDLI_MAJOR_DASHA = 'GET_KUNDLI_MAJOR_DASHA'
export const SET_KUNDLI_MAJOR_DASHA = 'SET_KUNDLI_MAJOR_DASHA'
export const GET_KUNDLI_SUB_V_DASHA = 'GET_KUNDLI_SUB_V_DASHA'
export const SET_KUNDLI_SUB_V_DASHA = 'SET_KUNDLI_SUB_V_DASHA'
export const SET_KUNDLI_DAHSA_VISIBLE = 'SET_KUNDLI_DAHSA_VISIBLE'
export const SET_KUNDLI_DASHA_PATH = 'SET_KUNDLI_DASHA_PATH'
export const GET_KUNDLI_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_V_DASHA'
export const GET_KUNDLI_SUB_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_SUB_V_DASHA'
export const GET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA = 'GET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA'
export const SET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA = 'SET_KUNDLI_SUB_SUB_SUB_SUB_V_DASHA'
export const GET_HOUSE_REPORTS = 'GET_HOUSE_REPORTS'
export const SET_HOUSE_REPORTS = 'SET_HOUSE_REPORTS'
export const GET_RASHI_REPORTS = 'GET_RASHI_REPORTS';
export const SET_RASHI_REPORTS = 'SET_RASHI_REPORTS';
export const GET_ASTAK_REPORTS = 'GET_ASTAK_REPORTS';
export const SET_ASTAK_REPORTS = 'SET_ASTAK_REPORTS';
export const GET_SARVA_REPORTS = 'GET_SARVA_REPORTS';
export const SET_SARVA_REPORTS = 'SET_SARVA_REPORTS';
export const GET_ASCEDENT_REPORTS = 'GET_ASCEDENT_REPORTS';
export const SET_ASCEDENT_REPORTS = 'SET_ASCEDENT_REPORTS';
export const GET_BASIC_PANCHANGE = 'GET_BASIC_PANCHANGE';
export const SET_BASIC_PANCHANGE = 'SET_BASIC_PANCHANGE';
export const GET_NUMERO_REPORT = 'GET_NUMERO_REPORT';
export const SET_NUMERO_REPORT = 'SET_NUMERO_REPORT';
export const GET_OPEN_NUMEROLOGY = 'GET_OPEN_NUMEROLOGY';
export const SET_OPEN_NUMEROLOGY = 'SET_OPEN_NUMEROLOGY';
export const GET_DELETE_NUMEROLOGY = 'GET_DELETE_NUMEROLOGY';
export const SET_DELETE_NUMEROLOGY = 'SET_DELETE_NUMEROLOGY';

export const GET_PANCHANG_MONTHLY = 'GET_PANCHANG_MONTHLY';
export const SET_PANCHANG_MONTHLY = 'SET_PANCHANG_MONTHLY';

export const GET_PANCHANG_MUHURAT = 'GET_PANCHANG_MUHURAT';
export const SET_PANCHANG_MUHURAT = 'SET_PANCHANG_MUHURAT';


export const GET_RULING_PLANETS = 'GET_RULING_PLANETS';
export const SET_RULING_PLANETS = 'SET_RULING_PLANETS';

export const GET_KP_CUSPS = 'GET_KP_CUSPS';
export const SET_KP_CUSPS = 'SET_KP_CUSPS';

export const GET_PLANETS = 'GET_PLANETS';
export const SET_PLANETS = 'SET_PLANETS';

export const GET_YOGINA_DASHA = 'GET_YOGINA_DASHA';
export const SET_YOGINA_DASHA = 'SET_YOGINA_DASHA';


export const GET_CURRENT_VIM_DASHA = 'GET_CURRENT_VIM_DASHA';
export const SET_CURRENT_VIM_DASHA = 'SET_CURRENT_VIM_DASHA';

export const GET_CURRENT_YOGINI_DASHA = 'GET_CURRENT_YOGINI_DASHA';
export const SET_CURRENT_YOGINI_DASHA = 'SET_CURRENT_YOGINI_DASHA';

export const GET_ANTAR_YOGINI_DASHA = 'GET_ANTAR_YOGINI_DASHA';
export const SET_ANTAR_YOGINI_DASHA = 'SET_ANTAR_YOGINI_DASHA';

export const GET_MANGAL_DOSHA = 'GET_MANGAL_DOSHA';
export const SET_MANGAL_DOSHA = 'SET_MANGAL_DOSHA';

export const GET_PITR_DOSHA = 'GET_PITR_DOSHA';
export const SET_PITR_DOSHA = 'SET_PITR_DOSHA';

export const GET_KP_BIRTH_CHART = 'GET_KP_BIRTH_CHART';
export const SET_KP_BIRTH_CHART = 'SET_KP_BIRTH_CHART';

export const GET_KP_CUPS_CHART = 'GET_KP_CUPS_CHART';
export const SET_KP_CUPS_CHART = 'SET_KP_CUPS_CHART';

export const GET_TRANSIT_CHART = 'GET_TRANSIT_CHART';
export const SET_TRANSIT_CHART = 'SET_TRANSIT_CHART';



export const GET_SWANSHA_CHART = 'GET_SWANSHA_CHART';
export const SET_SWANSHA_CHART = 'SET_SWANSHA_CHART';


export const GET_DASHAMANSHA_CHART = 'GET_DASHAMANSHA_CHART';
export const SET_DASHAMANSHA_CHART = 'SET_DASHAMANSHA_CHART';

export const GET_DWADASHAMANSHA_CHART = 'GET_DWADASHAMANSHA_CHART';
export const SET_DWADASHAMANSHA_CHART = 'SET_DWADASHAMANSHA_CHART';

export const GET_TRISHAMANSHA_CHART = 'GET_TRISHAMANSHA_CHART';
export const SET_TRISHAMANSHA_CHART = 'SET_TRISHAMANSHA_CHART';

export const GET_SHASHTYMANSHA_CHART = 'GET_SHASHTYMANSHA_CHART';
export const SET_SHASHTYMANSHA_CHART = 'SET_SHASHTYMANSHA_CHART';

export const GET_NAVAMANSHA_CHART = 'GET_NAVAMANSHA_CHART';
export const SET_NAVAMANSHA_CHART = 'SET_NAVAMANSHA_CHART';

export const GET_DRESHKAN_CHART = 'GET_DRESHKAN_CHART';
export const SET_DRESHKAN_CHART = 'SET_DRESHKAN_CHART';

export const GET_SUN2_CHART = 'GET_SUN2_CHART';
export const SET_SUN2_CHART = 'SET_SUN2_CHART';

export const GET_MOON2_CHART = 'GET_MOON2_CHART';
export const SET_MOON2_CHART = 'SET_MOON2_CHART';

export const GET_LAGNA_CHART = 'GET_LAGNA_CHART';
export const SET_LAGNA_CHART = 'SET_LAGNA_CHART';

export const GET_KUNDLI_D7_CHARTS = "GET_KUNDLI_D7_CHARTS"
export const SET_KUNDLI_D7_CHARTS = "SET_KUNDLI_D7_CHARTS"
export const GET_KUNDLI_D9_CHARTS = "GET_KUNDLI_D9_CHARTS"
export const SET_KUNDLI_D9_CHARTS = "SET_KUNDLI_D9_CHARTS"

export const GET_KUNDLI_CHART_DX = 'GET_KUNDLI_CHART_DX'
export const SET_KUNDLI_CHART_DX = 'SET_KUNDLI_CHART_DX'

export const GET_KUNDLI_HOUSES = 'GET_KUNDLI_HOUSES'
export const SET_KUNDLI_HOUSES = 'SET_KUNDLI_HOUSES'
export const GET_KUNDLI_DRISHTI = 'GET_KUNDLI_DRISHTI'
export const SET_KUNDLI_DRISHTI = 'SET_KUNDLI_DRISHTI'
export const GET_KUNDLI_MAITRI = 'GET_KUNDLI_MAITRI'
export const SET_KUNDLI_MAITRI = 'SET_KUNDLI_MAITRI'
export const GET_KUNDLI_REPORT = 'GET_KUNDLI_REPORT'
export const SET_KUNDLI_REPORT = 'SET_KUNDLI_REPORT'
export const GET_KUNDLI_TEST = 'GET_KUNDLI_TEST'

export const GET_KUNDLI_MATCHING_REPORT_POINTS = 'GET_KUNDLI_MATCHING_REPORT_POINTS'
export const SET_KUNDLI_MATCHING_REPORT_POINTS = 'SET_KUNDLI_MATCHING_REPORT_POINTS'
export const GET_KUNDLI_MATCHING_DSHKOOT_POINTS = 'GET_KUNDLI_MATCHING_DSHKOOT_POINTS'
export const SET_KUNDLI_MATCHING_DSHKOOT_POINTS = 'SET_KUNDLI_MATCHING_DSHKOOT_POINTS'
export const GET_KUNDLI_MATCHING_CONCLUSION_POINTS = 'GET_KUNDLI_MATCHING_CONCLUSION_POINTS'
export const SET_KUNDLI_MATCHING_CONCLUSION_POINTS = 'SET_KUNDLI_MATCHING_CONCLUSION_POINTS'

export const GET_KAALSARP_DATA = 'GET_KAALSARP_DATA'
export const SET_KAALSARP_DATA = 'SET_KAALSARP_DATA'

export const GET_GUN_DATA = 'GET_GUN_DATA'
export const SET_GUN_DATA = 'SET_GUN_DATA'

export const GET_ASTKOOT_DOSA = 'GET_ASTKOOT_DOSA'
export const SET_ASTKOOT_DOSA = 'SET_ASTKOOT_DOSA'

export const GET_MATCHING_PREDICTION = 'GET_MATCHING_PREDICTION'
export const SET_MATCHING_PREDICTION = 'SET_MATCHING_PREDICTION'


export const GET_DOSHA_REMEDIES = 'GET_DOSHA_REMEDIES'
export const SET_DOSHA_REMEDIES = 'SET_DOSHA_REMEDIES'

export const GET_MATCH_MAGLIK = 'GET_MATCH_MAGLIK'
export const SET_MATCH_MAGLIK = 'SET_MATCH_MAGLIK'

export const GET_MATCH_CONCLUSION = 'GET_MATCH_CONCLUSION'
export const SET_MATCH_CONCLUSION = 'GET_MATCH_CONCLUSION'

export const GET_CHALIT_CHART = 'GET_CHALIT_CHART';
export const SET_CHALIT_CHART = 'SET_CHALIT_CHART';

export const GET_MOON_CHART = 'GET_MOON_CHART';
export const SET_MOON_CHART = 'SET_MOON_CHART';

export const GET_DURMAHURAT = 'GET_DURMAHURAT';
export const SET_DURMAHURAT = 'SET_DURMAHURAT';


export const GET_ABHIJEET_MAHURAT = 'GET_ABHIJEET_MAHURAT';
export const SET_ABHIJEET_MAHURAT = 'SET_ABHIJEET_MAHURAT';

//Kundli Matching
export const SET_MALE_KUNDLI_DATA = 'SET_MALE_KUNDLI_DATA'
export const SET_FEMALE_KUNDLI_DATA = 'SET_FEMALE_KUNDLI_DATA'
export const GET_KUNDLI_MATCHING_REPORT = 'GET_KUNDLI_MATCHING_REPORT'
export const GET_KUNDLI_MATCHING_ASHTAKOOT_POINTS = 'GET_KUNDLI_MATCHING_ASHTAKOOT_POINTS'
export const SET_KUNDLI_MATCHING_ASHTAKOOT_POINTS = 'SET_KUNDLI_MATCHING_ASHTAKOOT_POINTS'
export const VIEW_KUNDLI_FROM_KUNDLI_MATCHING = 'VIEW_KUNDLI_FROM_KUNDLI_MATCHING'
export const SET_KUNDLI_BASIC_DETAILS_MATCHING = 'SET_KUNDLI_BASIC_DETAILS_MATCHING'
export const GET_KUNDLI_BASIC_DETAILS_MATCHING = 'GET_KUNDLI_BASIC_DETAILS_MATCHING'
export const SET_BASIC_ASTRO_POINTS = 'SET_BASIC_ASTRO_POINTS'
export const GET_BASIC_ASTRO_POINTS = 'GET_BASIC_ASTRO_POINTS'
export const GET_ASCEDENT_MATCHING_REPORTS = "GET_ASCEDENT_MATCHING_REPORTS"
export const SET_ASCEDENT_MATCHING_REPORTS = 'SET_ASCEDENT_MATCHING_REPORTS'
export const ON_KUNDLI_MATCHING = 'ON_KUNDLI_MATCHING';
export const GET_KUNDLI_MATCHING = 'GET_KUNDLI_MATCHING';
export const SET_KUNDLI_MATCHING = 'SET_KUNDLI_MATCHING';
export const DELETE_KUNDLI_MATCHING = 'DELETE_KUNDLI_MATCHING';
export const ON_MATCHING_DATA = 'ON_MATCHING_DATA';
export const SET_MATCHING_DATA = 'SET_MATCHING_DATA';
export const GET_MATCHING_DATA = 'GET_MATCHING_DATA';
export const ON_MATCHING_DELETE = 'ON_MATCHING_DELETE';


//Blogs
export const GET_RELIGION_AND_SPIRITUALITY = 'GET_RELIGION_AND_SPIRITUALITY'
export const SET_RELIGION_AND_SPIRITUALITY = 'SET_RELIGION_AND_SPIRITUALITY'
export const GET_BRIHAT_HOROSCOPE = 'GET_BRIHAT_HOROSCOPE'
export const SET_BRIHAT_HOROSCOPE = 'SET_BRIHAT_HOROSCOPE'
export const GET_TUTORIALS = 'GET_TUTORIALS'
export const SET_TUTORIALS = 'SET_TUTORIALS'
export const GET_MAGAZINE_DATA = 'GET_MAGAZINE_DATA'
export const SET_MAGAZINE_DATA = 'SET_MAGAZINE_DATA'
export const GET_REMEDIES_DATA = 'GET_REMEDIES_DATA'
export const SET_REMEDIES_DATA = 'SET_REMEDIES_DATA'
export const GET_DAILY_PUNCHANG_DATA = 'GET_DAILY_PUNCHANG_DATA'
export const SET_DAILY_PUNCHANG_DATA = 'SET_DAILY_PUNCHANG_DATA'
export const GET_YELLOW_BOOK_DATA = 'GET_YELLOW_BOOK_DATA'
export const SET_YELLOW_BOOK_DATA = 'SET_YELLOW_BOOK_DATA'
export const GET_AUSPICIOUS_DATA = 'GET_AUSPICIOUS_DATA'
export const SET_AUSPICIOUS_DATA = 'SET_AUSPICIOUS_DATA'
export const GET_ASTRO_BLOGS = 'GET_ASTRO_BLOGS'
export const SET_ASTRO_BLOGS = 'SET_ASTRO_BLOGS'
export const GET_ASTRO_BLOGS_CATEGORY = 'GET_ASTRO_BLOGS_CATEGORY';
export const SET_ASTRO_BLOGS_CATEGORY = 'SET_ASTRO_BLOGS_CATEGORY'


//Ecommerce
export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY'
export const SET_PRODUCT_CATEGORY = 'SET_PRODUCT_CATEGORY'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_CART_DATA = 'GET_CART_DATA'
export const SET_CART_DATA = 'SET_CART_DATA'
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY'
export const ORDER_CART = 'ORDER_CART'
export const GET_MALL_ORDER_DATA = 'GET_MALL_ORDER_DATA'
export const SET_MALL_ORDER_DATA = 'SET_MALL_ORDER_DATA'

//Astromall
export const GET_ASTROMALL_DATA = 'GET_ASTRO_MALL_DATA'
export const SET_ASTROMALL_POOJA_DATA = 'SET_ASTROMALL_POOJA_DATA'
export const SET_ASTROMALL_SPELL_DATA = 'SET_ASTROMALL_SPELL_DATA'
export const GET_ASTROLOGER_POOJA_DATA = 'GET_ASTROLOGER_POOJA_DATA'
export const SET_ASTROLOGER_POOJA_DATA = 'SET_ASTROLOGER_POOJA_DATA'
export const ORDER_ASTROLOGER_POOJA = 'ORDER_ASTROLOGER_POOJA'
export const GET_ASTROMALL_HISTORY = 'GET_ASTROMALL_HISTORY'
export const SET_ASTROMALL_HISTORY = 'SET_ASTROMALL_HISTORY'

//Rmove the card
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'

export const GET_TEMPLE_GIF = 'GET_TEMPLE_GIF'
export const SET_TEMPLE_GIF = 'SET_TEMPLE_GIF'

export const GET_SANATAN_TEMPLE_GIF = 'GET_SANATAN_TEMPLE_GIF'
export const SET_SANATAN_TEMPLE_GIF = 'SET_SANATAN_TEMPLE_GIF'

export const GET_ABHIJIT_MUHURT = 'GET_ABHIJIT_MUHURT'
export const SET_ABHIJIT_MUHURT = 'SET_ABHIJIT_MUHURT'

export const GET_DUR_MUHURAT = 'GET_DUR_MUHURAT'
export const SET_DUR_MUHURAT = 'SET_DUR_MUHURAT'

export const GET_GULIK_MUHURAT = 'GET_GULIK_MUHURAT'
export const SET_GULIK_MUHURAT = 'SET_GULIK_MUHURAT'

export const GET_YAM_MUHURAT = 'GET_YAM_MUHURAT'
export const SET_YAM_MUHURAT = 'SET_YAM_MUHURAT'


export const GET_YOG_DATA = 'GET_YOG_DATA'
export const SET_YOG_DATA = 'SET_YOG_DATA'



//PANCHANG 

export const GET_PANCHANG_DATA = 'GET_PANCHANG_DATA'

export const SET_PANCHANG_DATA = 'SET_PANCHANG_DATA'

export const GET_PANCHANG_MONTH_DATA = 'GET_PANCHANG_MONTH_DATA'
export const SET_PANCHANG_MONTH_DATA = 'SET_PANCHANG_MONTH_DATA'

//MUHURAT 
export const GET_MUHURAT_DATA = 'GET_MUHURAT_DATA'

export const SET_MUHURAT_DATA = 'SET_MUHURAT_DATA'

export const GET_MUHURAT_DUR_DATA = 'GET_MUHURAT_DUR_DATA'
export const SET_MUHURAT_DUR_DATA = 'SET_MUHURAT_DUR_DATA'

// CHOGADIYA

export const GET_CHOGADIYA_DATA = 'GET_CHOGADIYA_DATA'
export const SET_CHOGADIYA_DATA = 'SET_CHOGADIYA_DATA'

//Cart

export const ON_ADDRESS_CART = 'ON_ADDRESS_CART';
export const SET_ADDRESS_CART = 'SET_ADDRESS_CART';
export const GET_ADDRESS_CART = 'GET_ADDRESS_CART';
export const SET_SELECTED_ADDRESS_CART = 'SET_SELECTED_ADDRESS_CART';


export const SET_DELETE_CART = 'SET_DELETE_CART';
export const GET_DELETE_CART = 'GET_DELETE_CART';

export const SET_UPDATE_ADDRESS = 'SET_UPDATE_ADDRESS';
export const GET_UPDATE_ADDRESS = 'GET_UPDATE_ADDRESS';

//Virtue of visiting famout temples (Live)
export const GET_LIVE_TEMPLE_DATA = 'GET_LIVE_TEMPLE_DATA';
export const SET_LIVE_TEMPLE_DATA = 'SET_LIVE_TEMPLE_DATA';

// AJ KA PRADHAN

export const GET_PRADHAN_DATA = 'GET_PRADHAN_DATA'
export const SET_PRADHAN_DATA = 'SET_PRADHAN_DATA'

export const GET_MUDRA_DATA = 'GET_MUDRA_DATA'
export const SET_MUDRA_DATA = 'SET_MUDRA_DATA'


export const GET_LOTA_MUDRA_DATA = 'GET_LOTA_MUDRA_DATA'
export const SET_LOTA_MUDRA_DATA = 'SET_LOTA_MUDRA_DATA'

export const GET_BAGHWAN_DATA = 'GET_BAGHWAN_DATA'
export const SET_BAGHWAN_DATA = 'SET_BAGHWAN_DATA'

export const GET_BAGHWAN_DATA_NAVGRAH = 'GET_BAGHWAN_DATA_NAVGRAH'
export const SET_BAGHWAN_DATA_NAVGRAH = 'SET_BAGHWAN_DATA_NAVGRAH'

export const GET_BAGHWAN_DATA_VR_MODE = 'GET_BAGHWAN_DATA_VR_MODE';
export const SET_BAGHWAN_DATA_VR_MODE = 'SET_BAGHWAN_DATA_VR_MODE';


export const GET_POOJA_CATEGORY = 'GET_POOJA_CATEGORY'
export const SET_POOJA_CATEGORY = 'SET_POOJA_CATEGORY'

//Book Puja
export const GET_PUJA_DETAILS = 'GET_PUJA_DETAILS';
export const SET_PUJA_DETAILS = 'SET_PUJA_DETAILS';

//Gift
export const GET_GIFTS_DATA = 'GET_GIFTS_DATA';
export const SET_GIFTS_DATA = 'SET_GIFTS_DATA';

//Search

export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';

// Gifts Send and request

export const GET_SEND_GIFTS_DATA = 'GET_SEND_GIFTS_DATA';
export const SET_SEND_GIFTS_DATA = 'SET_SEND_GIFTS_DATA';
export const GET_SEND_GIFT_REQUEST = 'GET_SEND_GIFT_REQUEST';
export const SET_SEND_GIFT_REQUEST = 'SET_SEND_GIFT_REQUEST';
export const GET_SEND_REQUEST_DATA = 'GET_SEND_REQUEST_DATA'
export const SET_SEND_REQUEST_DATA = 'SET_SEND_REQUEST_DATA';
export const ON_RESPOND_WALLET_REQUEST = 'ON_RESPOND_WALLET_REQUEST'


// Sanatan
export const GET_SANTAN_FLOWER_VISIBLE = 'GET_SANTAN_FLOWER_VISIBLE'
export const SET_SANTAN_FLOWER_VISIBLE = 'SET_SANTAN_FLOWER_VISIBLE'
export const GET_SANTAN_SOUND_AARTI = 'GET_SANTAN_SOUND_AARTI';
export const SET_SANTAN_SOUND_AARTI = 'SET_SANTAN_SOUND_AARTI';
export const GET_SANTAN_SOUND_SHANKH = 'GET_SANTAN_SOUND_SHANKH'
export const SET_SANTAN_SOUND_SHANKH = 'SET_SANTAN_SOUND_SHANKH'
export const GET_SANTAN_SOUND_COCOUNT = 'GET_SANTAN_SOUND_COCOUNT'
export const SET_SANTAN_SOUND_COCOUNT = 'SET_SANTAN_SOUND_COCOUNT'
export const GET_SANTAN_SOUND_BELL = 'GET_SANTAN_SOUND_BELL'
export const GET_SANTAN_SOUND_BELL_2 = 'GET_SANTAN_SOUND_BELL_2'
export const SET_SANTAN_SOUND_BELL = 'SET_SANTAN_SOUND_BELL'
export const SET_SANTAN_SOUND_BELL_2 = 'SET_SANTAN_SOUND_BELL_2'
export const GET_SANTAN_SOUND_PLAY_SOUND = 'GET_SANTAN_SOUND_PLAY_SOUND'
export const SET_SANTAN_SHOW_NORMAL_THALI_VISIBLE = 'SET_SANTAN_SHOW_NORMAL_THALI_VISIBLE'
export const SET_SANTAN_SHOW_ROTATE_THALI_VISIBLE = 'SET_SANTAN_SHOW_ROTATE_THALI_VISIBLE'
export const GET_SANTAN_SHOW_THALI = 'GET_SANTAN_SHOW_THALI'
export const GET_SANTAN_THALI = 'GET_SANTAN_THALI';
export const GET_SANTAN_SHOW_THALI_ANIMATION = 'GET_SANTAN_SHOW_THALI_ANIMATION'
export const SET_SANTAN_SHOW_GIFT_BELL_VISIBLE = 'SET_SANTAN_SHOW_GIFT_BELL_VISIBLE'
export const SET_SANTAN_SHOW_GIFT_BELL_VISIBLE_2 = 'SET_SANTAN_SHOW_GIFT_BELL_VISIBLE_2'
export const SET_SANTAN_SHOW_IMAGE_BELL_VISIBLE = 'SET_SANTAN_SHOW_IMAGE_BELL_VISIBLE'
export const SET_SANTAN_SHOW_IMAGE_BELL_VISIBLE_2 = 'SET_SANTAN_SHOW_IMAGE_BELL_VISIBLE_2'
export const SET_SHOW_LOTTIE_MUDRA = 'SET_SHOW_LOTTIE_MUDRA'
export const SET_SHOW_SHOWER_VISIBLE = 'SET_SHOW_SHOWER_VISIBLE'
export const SET_SANTAN_SELECTED_TOP = 'SET_SANTAN_SELECTED_TOP'
export const GET_SANTAN_SELECTED_TOP = 'GET_SANTAN_SELECTED_TOP'
export const GET_SANTAN_VISIBEL_INDEX = 'GET_SANTAN_VISIBEL_INDEX'
export const SET_SANTAN_VISIBLE_INDEX = 'SET_SANTAN_VISIBLE_INDEX'
export const SET_SANTAN_NAVGARH_VISIBLE_INDEX = 'SET_SANTAN_NAVGARH_VISIBLE_INDEX'
export const SET_FLOWER_IMAGE = 'SET_FLOWER_IMAGE'
export const SET_SANTAN_AUDIO_SELECTED = 'SET_SANTAN_AUDIO_SELECTED'
export const SET_SANTAN_ACTIVE_CATEGORY = 'SET_SANTAN_ACTIVE_CATEGORY'
export const SET_SANTAN_CURRENT_INDEX = 'SET_SANTAN_CURRENT_INDEX'
export const GET_SANTAN_MY_THALI = 'GET_SANTAN_MY_THALI'
export const SET_SANTAN_MY_THALI = 'SET_SANTAN_MY_THALI'
export const SET_SANTAN_SPIN_VALUE = 'SET_SANTAN_SPIN_VALUE'
export const GET_SANTAN_FOOL_ARPAN = 'GET_SANTAN_FOOL_ARPAN'
export const GET_SANTAN_COCOUNT_ARPAN = 'GET_SANTAN_COCOUNT_ARPAN'
export const SET_SANTAN_COCOUNT_VISIBLE = 'SET_SANTAN_COCOUNT_VISIBLE'
export const SET_SANTAN_SETUP_PLAYER = 'SET_SANTAN_SETUP_PLAYER'
export const SET_SANTAN_CURRENT_SONG_INDEX = 'SET_SANTAN_CURRENT_SONG_INDEX'
export const SET_SANTAN_SONG_CURRENT_STATE = 'SET_SANTAN_SONG_CURRENT_STATE'
export const GET_SANTAN_SONG_CURRENT_STATE_UPDATE = 'GET_SANTAN_SONG_CURRENT_STATE_UPDATE'
export const SET_SANTAN_SOUND_CURRENT_STATE = 'SET_SANTAN_SOUND_CURRENT_STATE'
export const SET_SANTAN_NORMAL_GIF = 'SET_SANTAN_NORMAL_GIF'
export const SET_SANTAN_CURRENT_SONG = 'SET_SANTAN_CURRENT_SONG'
export const SET_SANTAN_IS_PLAYING = 'SET_SANTAN_IS_PLAYING'
export const SET_SANTAN_SLIDER_VALUE = 'SET_SANTAN_SLIDER_VALUE'
export const SET_SANTAN_DURATION_SOUND = 'SET_SANTAN_DURATION_SOUND'
export const GET_SANTAN_INTERVAL_SOUND_TIME = 'GET_SANTAN_INTERVAL_SOUND_TIME'
export const GET_SANTAN_SHANKH_PLAY = 'GET_SANTAN_SHANKH_PLAY'
export const SHOW_SANTAN_SHANKH_VISIBLE = 'SHOW_SANTAN_SHANKH_VISIBLE'
export const ON_VARDAN_SHIVALYA_DEDUCT = 'ON_VARDAN_SHIVALYA_DEDUCT'
export const ON_VARDAN_DAY_RESET = 'ON_VARDAN_DAY_RESET';
export const ON_SHIVALYA_DEDUCT = 'ON_SHIVALYA_DEDUCT'
export const ON_SHIVALYA_DAY_RESET = 'ON_SHIVALYA_DAY_RESET'


//Religion Collection

export const GET_ALL_RELIGION_COLLECTION = 'GET_ALL_RELIGION_COLLECTION'
export const SET_ALL_RELIGION_COLLECTION = 'SET_ALL_RELIGION_COLLECTION'

export const GET_ALL_RELIGION_COLLECTION_SUB_CATGORY = 'GET_ALL_RELIGION_COLLECTION_SUB_CATGORY'
export const SET_ALL_RELIGION_COLLECTION_SUB_CATGORY = 'SET_ALL_RELIGION_COLLECTION_SUB_CATGORY'


export const GET_TESTMONIAL_DATA = 'GET_TESTMONIAL_DATA'
export const SET_TESTMONIAL_DATA = 'SET_TESTMONIAL_DATA'


// ecommerce new

export const GET_ECOMMERCE_CATEGORY = 'GET_ECOMMERCE_CATEGORY';
export const SET_ECOMMERCE_CATEGORY = 'SET_ECOMMERCE_CATEGORY';
export const GET_ECOMMERCE_PRODUCT = 'GET_ECOMMERCE_PRODUCT';
export const SET_ECOMMERCE_PRODUCT = 'SET_ECOMMERCE_PRODUCT';
export const ON_ECOMMERCE_CART_ADD = 'ON_ECOMMERCE_CART_ADD';
export const GET_ECOMMERCE_CART = 'GET_ECOMMERCE_CART';
export const SET_ECOMMERCE_CART = 'SET_ECOMMERCE_CART';
export const ON_ECOMMERCE_REMOVE_CART = 'ON_ECOMMERCE_REMOVE_CART';
export const ON_ECOMMERCE_UPDATE_QUANITITY = 'ON_ECOMMERCE_UPDATE_QUANITITY'
export const ON_ECOMMERCE_ADD_ADDRESS = 'ON_ECOMMERCE_ADD_ADDRESS'
export const GET_ECOMMERCE_GET_ADDRESS = 'GET_ECOMMERCE_GET_ADDRESS'
export const SET_ECOMMERCE_ADRESS_DATA = 'SET_ECOMMERCE_ADRESS_DATA'
export const ON_ECOMMERCE_DELETE_ADDRESS = 'ON_ECOMMERCE_DELETE_ADDRESS'
export const ON_ECOMMERCE_RAZORPAY_ORDER = 'ON_ECOMMERCE_RAZORPAY_ORDER'
export const SET_ECOMMERCE_ORDER_HISTORY = 'SET_ECOMMERCE_ORDER_HISTORY'
export const GET_ECOMMERCE_ORDER_HISTORY = 'GET_ECOMMERCE_ORDER_HISTORY'


export const SET_BOTTOM_LEFT = 'SET_BOTTOM_LEFT';
export const SET_ADDRESS_MODAL_VISIBLE = 'SET_ADDRESS_MODAL_VISIBLE'

export const GET_VARDAN_SHIVALYA_DATA = 'GET_VARDAN_SHIVALYA_DATA'
export const SET_VARDAN_SHIVALYA_DATA = 'SET_VARDAN_SHIVALYA_DATA'

// VR and AR
export const ON_BELL_RING = 'ON_BELL_RING';
export const SET_BELL_RING = 'SET_BELL_RING';
export const ON_DIYA_ANIMATION = 'ON_DIYA_ANIMATION';
export const SET_DIYA_ANIMATION = 'SET_DIYA_ANIMATION';
export const GET_VR_ITEAMS = 'GET_VR_ITEAMS';
export const SET_VR_ITEAMS = 'SET_VR_ITEAMS';

export const SHOW_GIF = 'SHOW_GIF';
export const SET_BELL_GIF = 'SET_BELL_GIF';
export const SET_PUJA_GIF = 'SET_PUJA_GIF';
export const SET_COCOUNT_GIF = 'SET_COCOUNT_GIF';
export const SET_SHOW_ANIMATION = 'SET_SHOW_ANIMATION';
export const SET_IMAGE_ANIMATION = 'SET_IMAGE_ANIMATION';

export const ON_VR_DEDUCT_ADD = 'ON_VR_DEDUCT_ADD';
export const UPDATE_VR_USER_COUNT = 'UPDATE_VR_USER_COUNT';

export const CHANGE_VR_IMAGE = 'CHANGE_VR_IMAGE';


//Offer Recharge
export const CHECK_OFFER = 'CHECK_OFFER';
export const SET_CHECK_OFFER = 'SET_CHECK_OFFER';
export const GET_CIRCLE_LIST = 'GET_CIRCLE_LIST';
export const SET_CIRCLE_LIST = 'SET_CIRCLE_LIST';

export const GET_HLR_LOOKUP = 'GET_HLR_LOOKUP'
export const SET_HLR_LOOKUP = 'SET_HLR_LOOKUP'

export const SET_SELECTED_RECHARGE = 'SET_SELECTED_RECHARGE'
export const SET_RECHARGE_RUPEE = 'SET_RECHARGE_RUPEE'

export const GET_RECHARGE_DATA = 'GET_RECHARGE_DATA'
export const CHECK_BALANCE_PAY_NEW = 'CHECK_BALANCE_PAY_NEW'

export const SET_SELECTED_OPERATOR = 'SET_SELECTED_OPERATOR'

export const SET_ORDER_ID = 'SET_ORDER_ID';



export const GET_DTH_INFO = 'GET_DTH_INFO'
export const SET_DTH_INFO = 'SET_DTH_INFO'

export const GET_DTH_HEAVY_REFRESH = 'GET_DTH_HEAVY_REFRESH'
export const SET_DTH_HEAVY_REFRESH = 'SET_DTH_HEAVY_REFRESH'

export const GET_DTH_INFO_MOBILE = 'GET_DTH_INFO_MOBILE'
export const SET_DTH_INFO_MOBILE = 'SET_DTH_INFO_MOBILE'

export const GET_FETCH_BILL_INFO = 'GET_FETCH_BILL_INFO'
export const SET_FETCH_BILL_INFO = 'SET_FETCH_BILL_INFO'
export const ON_BILL_PAYMENT = 'ON_BILL_PAYMENT'

// All Services 
export const GET_DTH_OPERATOR = 'GET_DTH_OPERATOR'
export const SET_DTH_OPERATOR = 'SET_DTH_OPERATOR'

export const GET_ALL_SERVICE_PROVIDERS = 'GET_ALL_SERVICE_PROVIDERS';
export const SET_ALL_SERVICE_PROVIDERS = 'SET_ALL_SERVICE_PROVIDERS';

export const GET_SERVICES_LIST = 'GET_SERVICES_LIST';
export const SET_SERVICES_LIST = 'SET_SERVICES_LIST';

//Queus Flow
export const GET_PREDEFINE_MESSAGE = 'GET_PREDEFINE_MESSAGE';
export const SET_PREDEFINE_MESSAGE = 'SET_PREDEFINE_MESSAGE';



//add to cart
export const GET_PUJA_ADD_TO_CART = 'GET_PUJA_ADD_TO_CART';
export const SET_PUJA_ADD_TO_CART = 'SET_PUJA_ADD_TO_CART';

// Image Camera
export const SET_IMAGE_DATA = 'SET_IMAGE_DATA'
export const SET_CAMERA_VISION_VISIBLE_CUSTOMER = 'SET_CAMERA_VISION_VISIBLE_CUSTOMER'
export const SET_CHAT_MODAL_VISIBLE = 'SET_CHAT_MODAL_VISIBLE'
export const SET_CHAT_BUTTON_VISIBLE = 'SET_CHAT_BUTTON_VISIBLE'



//new Astrologer
export const GET_NEW_ASTRO = 'GET_NEW_ASTRO';
export const SET_NEW_ASTRO = 'SET_NEW_ASTRO'


export const GET_MY_PANCHANG_DATA = 'GET_MY_PANCHANG_DATA';
export const SET_MY_PANCHANG_DATA = 'SET_MY_PANCHANG_DATA';



export const GET_MY_MAHURAT_DATA = 'GET_MY_MAHURAT_DATA';
export const SET_MY_MAHURAT_DATA = 'SET_MY_MAHURAT_DATA';


export const GET_MY_CHOGADIYA_DATA = 'GET_MY_CHOGADIYA_DATA';
export const SET_MY_CHOGADIYA_DATA = 'SET_MY_CHOGADIYA_DATA';



export const GET_MY_LETTER_PANCHANG = 'GET_MY_LETTER_PANCHANG';
export const SET_MY_LETTER_PANCHANG = 'SET_MY_LETTER_PANCHANG';

export const GET_MY_PANCHANG_YESTERDAY = 'GET_MY_PANCHANG_YESTERDAY';
export const SET_MY_PANCHANG_YESTERDAY = 'SET_MY_PANCHANG_YESTERDAY';

export const GET_MY_PANCHANG_TOMMOROW = 'GET_MY_PANCHANG_TOMMOROW';
export const SET_MY_PANCHANG_TOMMOROW = 'SET_MY_PANCHANG_TOMMOROW';



//Mobile Recharge
export const GET_DEVICE_CONTACTS = 'GET_DEVICE_CONTACTS'
export const SET_DEVICE_CONTACTS = 'SET_DEVICE_CONTACTS'
export const SET_MASTER_DEVICE_CONTACTS = 'SET_MASTER_DEVICE_CONTACTS'
export const GET_MOBILE_PLANS = 'GET_MOBILE_PLANS'
export const SET_MOBILE_PLANS = 'SET_MOBILE_PLANS'
export const SET_MASTER_MOBILE_PLANS = 'SET_MASTER_MOBILE_PLANS'

export const GET_RECHARGE = 'GET_RECHARGE'
export const SET_RECHARGE = 'SET_RECHARGE'
export const ON_RAZORPAY = 'ON_RAZORPAY'
export const SET_RAZORPAY = 'SET_RAZORPAY'
export const GET_RECHARGE_REQUEST_FIELDS = 'GET_RECHARGE_REQUEST_FIELDS'
export const SET_RECHARGE_REQUEST_FIELDS = 'SET_RECHARGE_REQUEST_FIELDS'
export const GET_RECHARGE_BILL_DETAILS = 'GET_RECHARGE_BILL_DETAILS'
export const SET_RECHARGE_BILL_DETAILS = 'SET_RECHARGE_BILL_DETAILS'
export const ON_CYRUS_RECHARGE = 'ON_CYRUS_RECHARGE'
// dth Recharge
export const GET_DTH_BILL_DETAILS = 'GET_DTH_BILL_DETAILS'
export const SET_DTH_VALIDATION = 'SET_DTH_Validation'
export const GET_DTH_Validation = 'GET_DTH_Validation'

//FastTag
export const ON_FASTTAG_RECHARGE = 'ON_FASTTAG_RECHARGE'
export const GET_FASTTAG_OPERATOR = 'GET_FASTTAG_OPERATOR'
export const SET_FASTTAG_OPERATOR = 'SET_FASTTAG_OPERATOR'

//Electric City
export const GET_ELECTRICITY_OPERATOR = 'GET_ELECTRICITY_OPERATOR'
export const SET_ELECTRICITY_OPERATOR = 'SET_ELECTRICITY_OPERATOR'
export const SET_TOKEN = "SET_TOKEN"

// Gas
export const GET_GAS_OPERATOR = 'GET_GAS_OPERATOR'
export const SET_GAS_OPERATOR = 'SET_GAS_OPERATOR'


export const GET_OPERATOR = 'GET_OPERATOR'
export const SET_OPERATOR = 'SET_OPERATOR'
export const GET_BILL_DETAILS = 'GET_BILL_DETAILS'
export const SET_BILL_DETAILS = 'SET_BILL_DETA'
//  operator and circle 

export const SET_OPT = 'SET_OPT'
export const SET_CIRCLE = 'SET_CIRCLE'
export const GET_OPT = 'SET_OPT'
export const GET_CIRCLE = 'SET_CIRCLE'
export const SET_BILLDATA = 'SET_BILLDATA'
export const GET_BILLDATA = 'GET_BILLDATA'
export const GET_POSTPAID_OPERATOR = 'GET_POSTPAID_OPERATOR'
export const SET_POSTPAID_OPERATOR = 'SET_POSTPAID_OPERATOR'



export const SERVICES_LIST_LOADING = 'SERVICES_LIST_LOADING';
export const SERVICES_LIST_ERROR = 'SERVICES_LIST_ERROR';



export const GET_HISTORY_DATA = 'GET_HISTORY_DATA'
export const SET_HISTORY_DATA = 'SET_HISTORY_DATA'

//Join
export const ON_JOIN = 'ON_JOIN';
export const SET_VISIBLE_HOME_MODAL = 'SET_VISIBLE_HOME_MODAL';

export const ON_RAZORPAY_TEST = 'ON_RAZORPAY_TEST';
